config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  root 'contacts#contacts'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contacts' => 'contacts#contacts'
  get 'newcontact' => 'contacts#new'
  get 'search' => 'contacts#search'
  resources :contacts
  resources :numbers,          only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :numbers, dependent: :destroy
  before_save { self.email = email.downcase }
  mount_uploader :picture, PictureUploader
  default_scope {order('name')}
  validates :name, presence: true, length: { maximum: 100 },  uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
            uniqueness: { case_sensitive: false } 
   validate  :picture_size

   private

   def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/models/number.rb
class Number < ApplicationRecord
  VALID_NUMBER = /[0-9]{1,3}-[0-9]{1,3}-[0-9]{1,10}/
  belongs_to :contact
  validates :contact_id, presence: true
  validates :num, presence: true, format: { with: VALID_NUMBER }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def show
    @contact = Contact.find(params[:id])
    @numbers = @contact.numbers.all
    @number = @contact.numbers.build
  end
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)  
    if @contact.save
      flash[:success] = "Успешно создан!"
      redirect_to @contact
    else
      render 'new'
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(contact_params)
      flash[:success] = "контакт редактирован!"
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def destroy
    Contact.find(params[:id]).destroy
    flash[:success] = "Контакт удален"
  end

  def contacts
    @contact = Contact.new
    @contacts = search.paginate(page: params[:page], :per_page   => 10)
  end

  def current_contact
    @current_contact = Contact.find(params[:id])
  end

  def search
    query = "#{params[:search]}"
    if /\d/.match(query)
      @contacts = Contact.joins(:numbers).where("num LIKE ?", "%#{query}%")
    else
      @contacts = Contact.where("name LIKE ?", "%#{query}%")
    end
  end

  private

    def contact_params
      param = params.require(:contact).permit(:name, :email, :picture)
      if param[:picture].nil?
        param[:picture] = default_picture
      end
      return param
    end

    def default_picture
      picture_number = (1..5).to_a.shuffle.first
      picture = File.open(File.join(Rails.root,"app/assets/images/defaultcat#{picture_number}.jpg"))
    end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController

  def create
    @contact = Contact.find(params[:contact])
    @number = @contact.numbers.create(number_params)
    if @number.save
      flash[:success] = "Успешно создан!"
      redirect_to @contact
    else
      flash[:success] = "неверно заполенное поле!"
      redirect_to @contact
    end
  end

  def destroy
    @number = Number.find(params[:id])
    @contact = Contact.find(@number.contact_id)
    @number.destroy
    # redirect_to @contact
  end

  private

  def number_params
    params.require(:number).permit(:num, :label)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Phone book"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/_contact.html.erb
<li>
  <div class = "userinfo">
    <div class = "left">
      <%= image_tag contact.picture.url if contact.picture? %>
    </div>
    <div class = "right">
      <p><name><%= link_to contact.name, contact %></name></p>
      <p><number>☎<%= (contact.numbers.where("label IS ?", "Мобильный").first || contact.numbers.first).num if contact.numbers.any? %> 
      </number></p>
      <p><number> ✉ <%= contact.email %></number> </p>
    </div>
</div>
  
  
  <div class = "delete_cat" style='text-align: right;'><%= link_to "Выкинуть на мороз", contact, method: :delete,
                              data: { confirm: "Прямо выкинуть?" } %>                          	
   </div>
</li>

app/views/contacts/_list.html.erb
<ul class="users">
<div id = "main">
	<cats>____ Котики____</cats>
</div>
  <%= render @contacts %>
</ul>
<%= will_paginate %>

app/views/contacts/_new.html.erb
<section class="contact_form">
  <div class="new_cat_form">
    <%= form_for(@contact,  html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages' %>
    <div id = "right">
      <%= f.label :Имя %>
      <%= f.text_field :name, placeholder: 'котика зовут...', class: 'form-control' %>

      <%= f.label :Почта %>
      <%= f.email_field :email, placeholder: 'котику можно написать...', class: 'form-control' %>
    </div>
      <div id = left>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: "inputfile"%>
       <%= label_tag :contact_picture, "выберите картинку с котиком", id: "label" %>
      <p><%= f.submit "Добавить", class: "button" %></p></div>
    <% end %>  

  </div>

app/views/contacts/_search_form.html.erb
<nav class="navbar navbar-light" >
  <%= form_with(url: "/contacts", method: "get", id: "contacts_search") do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Ищем котана!", :name => nil %>
<% end %>
</nav>

app/views/contacts/contacts.html.erb
<% provide(:title, 'All contacts') %>
 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  
  <div class="container">
    <div class="row">
      <!-- Trigger the modal with a button -->
      <button type="button" class = "button" data-toggle="modal" background-color = "#9b73a3" data-target="#myModal">Добавить котика</button>

      <div class="modal custom-m" background-color = "#e3bec3" id="myModal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content" >
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              
            </div>
            <div class="modal-body" background-color = "#e3bec3";>
              <%=render 'contacts/new' %>
            </div>
          </div>

        </div>
      </div>
      
    </div>
  </div>
<nav class="navbar navbar-light" >
 <%= render 'contacts/search_form' %>
</nav>
      

<div id="cats"><%=render 'contacts/list' %></div>

<script>
$('#cats').on('click', '.delete_cat', function() {
    $(this).closest('li').remove();
});
</script>

app/views/contacts/contacts.js.erb
$('#cats').html('<%= escape_javascript(render("list")) %>');

app/views/contacts/edit.html.erb
<% provide(:title, "Изменить контакт") %>
<h1>Изменить контакт</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@contact) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :Имя %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :Почта %>
      <%= f.email_field :email, class: 'form-control' %>

      <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

      <%= f.submit "Сохранить", class: "button" %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#contact_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Оченно большая картинка. Надо меньше.');
    }
  });
</script>

app/views/contacts/new.html.erb
<% provide(:title, 'new contact') %>
<h1>Новый контакт</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@contact,  html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :Имя %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :Почта %>
      <%= f.email_field :email, class: 'form-control' %>

      <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>

      <%= f.submit "Создать", class: "button" %>
    <% end %>  

  </div>
</div>

app/views/contacts/show.html.erb
<% provide(:title, @contact.name) %>
<div class="row" style ="background-color: #f1dddf;">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @contact.picture.url if @contact.picture? %>
      	<p>
          <%= @contact.name %>	
  	    </p>
  	    <p>
          <%= @contact.email %>
      	</p>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @contact.numbers.any? %>
      <ol class="numbers" id = "numbers">
        <%= render @numbers %>
      </ol>
    <% end %>
  </div>
</div>
  <li><%= link_to "Изменить", edit_contact_path(@contact) %></li>

 <section class="number_form">
      <%= render 'numbers/number_form' %>
</section>
 
<script>
$('#numbers').on('click', '.delete_number', function() {
    $(this).closest('li').remove();
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "О приложении",   about_path %></li>
      <li><%= link_to "Помощь", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
   <header class="navbar navbar-expand-lg navbar-dark">
       <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="<%= contacts_path %>"><h2>Контакты</h2> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= about_path %>"><h2>О приложении</h2></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= help_path %>"><h2>Помосчь</h2></a>
          </li>
        </ul>
      <div>
    </header>

app/views/layouts/_shim.html.erb
   <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
     <%= render 'layouts/shim' %>
  </head>
  <body style = "background-color: #e3bec3;">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/numbers/_number.html.erb
<li id="number-<%=number.id%>">
  <span class="content"><%= number.num %> <%= number.label %>   
  </span>
  <div class ="delete_number" style='text-align: right;'><%= link_to "Удалить", number, method: :delete, data: { confirm: "Удалить?" } %>                </div>   
</li>

app/views/numbers/_number_form.html.erb
<%= form_for(@number) do |f| %>
  <div class="field">
    <%= f.telephone_field :num, required: true, placeholder: "номер в формате хх-хх-ххххххх", pattern: "[0-9]{1,3}-[0-9]{1,3}-[0-9]{1,10}"%>
  </div>
 <div id = 'lab'>
 <%= f.select :label,  [['Мобильный', 'мобильный'], ['Служебный', 'служебный'], ['Домашний', 'домашний'], ['Другое', 4]] %>
</div>
  <%= f.submit "добавить", class: "button" %>
  <%= hidden_field_tag(:contact, @contact.id) %>
<% end %>

<script>

label = document.getElementById('number_label');
label.addEventListener("change", otherLabel);
function otherLabel() {
	div = document.createElement('div');
  	div.innerHTML = '<input name=number[label] id="number_l">';
  	if ($(this).val() == 4) {
	  	lab.append(div);
	  	} else {
	  		{
			if (removing_elem = document.getElementById("number_l")){
			removing_elem.remove();
			}
		}
  	}	
}

</script>

app/views/shared/_error_messages.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@contact.errors.count, "error") %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>Cat Book</h1>
    <p>
    	Просто пробное задание. Позволит систематизировать знакомых котиков.
    </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
     помоги себе сам!
    </p>
  </body>